# Generated by Django 6.0.4 on 2026-06-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_created_by'),
        ('users', '0018_user_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
