version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nsigned
  cms:
    build:
      context: ./apps/cms
    container_name: cms
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./apps/cms
        target: /app
        consistency: delegated
    networks:
      - nsigned
    env_file:
      - .env
      - apps/cms/.env
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - nsigned
volumes:
  postgres_data:
  frontend_node_modules:
networks:
  nsigned:
    driver: bridge
