# Generated by Django 6.0.4 on 2026-04-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_deleted_user_last_login_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('contributor', 'Contributor'), ('editor', 'Editor')], default='user', max_length=20),
        ),
    ]
