# Generated by Django 6.0.4 on 2026-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('editor', 'Editor')], default='contributor', max_length=20),
        ),
    ]
