# Generated by Django 6.0.4 on 2026-05-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('editor', 'Editor'), ('admin', 'Admin')], default='contributor', max_length=20),
        ),
    ]
