# Generated by Django 6.0.4 on 2026-05-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_created_by'),
        ('users', '0010_alter_user_fundraiser_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fundraiser_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_owners', to='links.link'),
        ),
    ]
