# Generated by Django 6.0.4 on 2026-05-18 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_fundraiser_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_expiry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
