# Generated by Django 6.0.4 on 2026-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_password_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_consent',
            field=models.BooleanField(default=False),
        ),
    ]
