# Generated by Django 6.0.4 on 2026-05-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_email_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_consent',
        ),
    ]
