# Generated by Django 6.0.4 on 2026-05-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_email_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_email',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
