# Generated by Django 6.0.4 on 2026-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
