# Generated by Django 6.0.4 on 2026-08-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_featuredauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patreon_id', models.IntegerField()),
                ('tier', models.CharField(choices=[('subscriber', 'Subscriber')], default='subscriber')),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
