# Generated by Django 6.0.4 on 2026-08-27 14:46

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_patreonuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreonuser',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patreonuser',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patreonuser',
            name='token_expires_at',
            field=models.DateTimeField(),
        ),
    ]
