# Generated by Django 6.0.4 on 2026-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_patreonuser_access_token_patreonuser_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patreonuser',
            name='tier',
            field=models.CharField(choices=[('supporter', 'Supporter')], default='supporter'),
        ),
    ]
