# Generated by Django 6.0.4 on 2026-04-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='links',
        ),
        migrations.CreateModel(
            name='ReleaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.release')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('link',), name='unique_link_per_release')],
            },
        ),
    ]
