# Generated by Django 6.0.4 on 2026-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('music', '0002_remove_release_links_releaselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='links',
            field=models.ManyToManyField(related_name='release_links', through='music.ReleaseLink', to='links.link'),
        ),
    ]
