# Generated by Django 6.0.4 on 2026-04-23 14:20

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('music', '0003_release_links'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='release',
            managers=[
                ('bandcamp', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='release',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='artist',
            name='bandcamp_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='label',
            name='bandcamp_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='release',
            name='image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='links.link'),
        ),
    ]
