# Generated by Django 6.0.4 on 2026-04-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_artist_created_by_alter_label_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='release',
            managers=[
            ],
        ),
    ]
