# Generated by Django 6.0.4 on 2026-04-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_release_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bandcamp_id',
        ),
        migrations.RemoveField(
            model_name='label',
            name='bandcamp_id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
