# Generated by Django 6.0.4 on 2026-04-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_artist_bandcamp_id_remove_label_bandcamp_id_and_more'),
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_review_requests', to='users.user')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.release', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
