# Generated by Django 6.0.4 on 2026-04-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_reviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.release'),
        ),
    ]
