# Generated by Django 6.0.4 on 2026-04-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_reviewrequest_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='release_date',
        ),
    ]
