# Generated by Django 6.0.4 on 2026-05-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_release_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='image_url',
        ),
    ]
