# Generated by Django 6.0.4 on 2026-05-01 13:03

import music.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_release_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='images',
            field=models.JSONField(default={}, validators=[music.validators.images_validator]),
            preserve_default=False,
        ),
    ]
