# Generated by Django 6.0.4 on 2026-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_created_by'),
        ('music', '0012_release_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='links',
            field=models.ManyToManyField(related_name='links', through='music.ReleaseLink', to='links.link'),
        ),
    ]
