# Generated by Django 6.0.4 on 2026-05-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_release_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
