# Generated by Django 6.0.4 on 2026-05-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_reviewrequest_rejected'),
        ('users', '0005_alter_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_review_requests', to='users.user'),
        ),
    ]
