# Generated by Django 6.0.4 on 2026-05-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_reviewrequest_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.release'),
        ),
    ]
