# Generated by Django 6.0.4 on 2026-05-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_alter_reviewrequest_release'),
        ('users', '0005_alter_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='users.user'),
        ),
    ]
