# Generated by Django 6.0.4 on 2026-05-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='notify_on_review',
            field=models.BooleanField(default=True),
        ),
    ]
