# Generated by Django 6.0.4 on 2026-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_reviewrequest_notify_on_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
