# Generated by Django 6.0.4 on 2026-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_reviewrequest_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='genre',
            field=models.CharField(blank=True, choices=[('rock-acoustic-metal', 'Rock//Acoustic//Metal'), ('hiphop-funk-rnb', 'Hip Hop//Funk//R&B'), ('electronic-dance-ambient', 'Electronic//Dance//Ambient'), ('experimental-weird', 'Experimental//Weird'), ('jazz', 'Jazz'), ('classical-orchestral-world', 'Classical//Orchestral//World')], max_length=50, null=True),
        ),
    ]
