# Generated by Django 6.0.4 on 2026-06-11 09:53

from django.db import migrations

rock = "rock-acoustic-metal"
hh = "hiphop-funk-rnb"
elec = "electronic-dance-ambient"
jazz = "jazz"
clas = "classical-world"
other = "experimental-weird"

def set_genres(apps, schema_editor):
    article_genre_map = (
        (4, rock),
        (5, jazz),
        (6, rock),
        (8, rock),
        (9, elec),
        (10, elec),
        (11, hh),
        (13, elec),
        (14, elec),
        (15, other),
        (16, elec),
        (17, rock),
        (18, other),
        (19, rock),
        (20, rock),
        (21, elec),
        (22, rock),
        (23, elec),
        (24, elec),
        (26, rock),
        (27, rock),
        (28, elec),
        (29, rock),
        (30, rock),
        (31, elec),
        (32, rock),
        (33, rock),
        (34, rock),
        (35, jazz),
        (36, clas),
        (37, hh),
        (38, rock),
        (39, hh),
        (40, elec),
        (41, rock),
        (42, other),
        (43, elec),
        (44, hh),
        (45, rock),
        (46, rock),
        (47, rock),
        (48, elec),
        (49, rock),
        (50, rock),
        (51, hh),
        (52, hh),
        (53, elec),
        (54, rock),
        (55, rock),
        (56, elec),
        (57, elec),
        (58, rock),
        (59, hh),
        (60, elec),
        (61, hh),
        (62, rock),
        (63, elec),
        (64, rock),
        (65, jazz),
        (66, hh),
        (67, other),
        (68, elec),
        (69, other),
        (70, rock),
        (71, rock),
        (72, rock),
        (73, elec),
        (74, elec),
        (75, other),
        (76, rock),
        (77, elec),
        (78, elec),
        (79, hh),
        (80, elec),
        (81, hh),
        (82, elec),
        (84, hh),
        (85, elec),
        (86, elec),
        (87, rock),
        (88, other),
        (89, hh),
        (90, hh),
        (92, elec),
        (93, rock),
        (94, rock),
        (95, hh),
    )
    release_genre_map = (
        (86, rock),
        (87, elec),
        (88, elec),
        (89, rock),
        (90, hh),
        (91, elec),
        (92, elec),
        (96, rock),
        (100, other),
        (102, elec),
        (103, rock),
        (104, rock),
        (105, clas),
        (106, rock),
        (107, elec),
        (108, rock),
        (109, rock),
        (110, jazz),
        (111, elec),
        (112, elec),
        (113, elec),
        (114, rock),
        (115, rock),
        (116, elec),
        (117, hh),
        (118, rock),
        (119, rock),
        (120, hh),
        (121, hh),
        (122, rock),
        (123, elec),
        (124, rock),
        (126, elec),
        (127, elec),
        (128, hh),
        (129, elec),
        (130, elec),
    )

    Release = apps.get_model("music", "Release")

    for (article_id, genre) in article_genre_map:
        Release.objects.filter(reviewrequest__article__id=article_id).update(genre=genre)

    for (release_id, genre) in release_genre_map:
        Release.objects.filter(id=release_id).update(genre=genre)

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_set_genres'),
    ]

    operations = [
        migrations.RunPython(set_genres, reverse_code=migrations.RunPython.noop)
    ]
