# Generated by Django 6.0.4 on 2026-06-11 11:10

from django.db import migrations

# Generated by Django 6.0.4 on 2026-06-11 09:53

from django.db import migrations


clas = "classical-orchestral-world"

def set_genres(apps, schema_editor):
    article_genre_map = (
        (36, clas),
    )
    release_genre_map = (
        (105, clas),
    )

    Release = apps.get_model("music", "Release")

    for (article_id, genre) in article_genre_map:
        Release.objects.filter(reviewrequest__article__id=article_id).update(genre=genre)

    for (release_id, genre) in release_genre_map:
        Release.objects.filter(id=release_id).update(genre=genre)

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_set_genres'),
    ]

    operations = [
    ]
