# Generated by Django 6.0.4 on 2026-06-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_created_by'),
        ('music', '0024_alter_artist_created_by_alter_label_created_by_and_more'),
        ('users', '0018_user_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='links',
            field=models.ManyToManyField(blank=True, to='links.link'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='users.user'),
        ),
    ]
