# Generated by Django 6.0.4 on 2026-06-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_alter_artist_links_alter_artist_user'),
        ('users', '0018_user_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_review_requests', to='users.user'),
        ),
    ]
