# Generated by Django 6.0.4 on 2026-08-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_bookmark_unique_bookmark_per_user_article'),
        ('music', '0026_alter_reviewrequest_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='featured_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article'),
        ),
        migrations.AddField(
            model_name='artist',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
