# Generated by Django 6.0.4 on 2026-07-02 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_alter_reviewrequest_rejected_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('wav_location', models.CharField(max_length=255)),
                ('mp3_location', models.CharField(max_length=255)),
                ('track_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.release')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('release', 'track_number'), name='unique_track_number_per_release')],
            },
        ),
    ]
