# Generated by Django 6.0.4 on 2026-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='source',
            field=models.CharField(choices=[('bandcamp', 'Bandcamp'), ('nsigned', '_nsigned')], default='bandcamp', max_length=30),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete')], default='processing', max_length=15),
        ),
    ]
