# Generated by Django 6.0.4 on 2026-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_track_created_at_track_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('removed', 'Removed')], default='processing', max_length=15),
        ),
    ]
