# Generated by Django 6.0.4 on 2026-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_alter_track_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
