# Generated by Django 6.0.4 on 2026-08-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_artist_bio_artist_featured_review_artist_video_url'),
        ('music', '0032_release_status'),
    ]

    operations = [
    ]
