# Generated by Django 6.0.4 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_merge_20260826_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='bandcamp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
