# Generated by Django 6.0.4 on 2026-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_release_bandcamp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='bandcamp_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
