# Generated by Django 6.0.4 on 2026-07-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0019_featuredauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filetype', models.CharField(choices=[('jpg', 'jpg'), ('png', 'png')], max_length=3)),
                ('lg_location', models.CharField(max_length=1000, unique=True)),
                ('md_location', models.CharField(max_length=1000, unique=True)),
                ('sm_location', models.CharField(max_length=1000, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
