# Generated by Django 6.0.4 on 2026-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='filetype',
            field=models.CharField(choices=[('jpg', 'jpg')], max_length=3),
        ),
    ]
