# Generated by Django 6.0.4 on 2026-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imageupload_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='filetype',
            field=models.CharField(choices=[('jpg', 'jpg'), ('png', 'png')], max_length=3),
        ),
    ]
