# Generated by Django 6.0.4 on 2026-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_imageupload_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='src_location',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
