# Generated by Django 6.0.4 on 2026-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_imageupload_src_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='src_location',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
