# Generated by Django 6.0.4 on 2026-04-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecontent_active_articlecontent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
