# Generated by Django 6.0.4 on 2026-04-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_at',
            new_name='created_at',
        ),
    ]
