# Generated by Django 6.0.4 on 2026-04-23 10:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_published_at'),
        ('users', '0002_user_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('cms', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='articles.article'),
        ),
    ]
