# Generated by Django 6.0.4 on 2026-04-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_managers_remove_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='external_link',
        ),
    ]
