# Generated by Django 6.0.4 on 2026-04-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_created_by_and_more'),
        ('links', '0002_alter_link_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='external_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.link'),
        ),
    ]
