# Generated by Django 6.0.4 on 2026-04-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_managers_article_external_link'),
        ('music', '0006_alter_release_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.release'),
        ),
    ]
