# Generated by Django 6.0.4 on 2026-04-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_release'),
        ('music', '0008_reviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='review_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.reviewrequest'),
        ),
    ]
