# Generated by Django 6.0.4 on 2026-05-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_review_request'),
        ('music', '0017_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='music.release'),
        ),
    ]
