# Generated by Django 6.0.4 on 2026-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='release',
        ),
    ]
