# Generated by Django 6.0.4 on 2026-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_external_link_remove_article_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
