# Generated by Django 6.0.4 on 2026-05-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_review_request'),
        ('music', '0017_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='review_request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.reviewrequest'),
        ),
    ]
