# Generated by Django 6.0.4 on 2026-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_comment_commentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='idempotency_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
