# Generated by Django 6.0.4 on 2026-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_comment_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='idempotency_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
