# Generated by Django 6.0.4 on 2026-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_comment_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
