# Generated by Django 6.0.4 on 2026-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_bookmark'),
        ('users', '0018_user_pronouns'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('created_by', 'article'), name='unique_bookmark_per_user_article'),
        ),
    ]
